-- Backfill schema columns for HR/CRM/Project modules to align with DTO/entity fields.

-- CRM
ALTER TABLE crm_stage ADD COLUMN IF NOT EXISTS name VARCHAR(64);
ALTER TABLE crm_stage ADD COLUMN IF NOT EXISTS sequence INTEGER;
ALTER TABLE crm_stage ADD COLUMN IF NOT EXISTS is_won BOOLEAN DEFAULT FALSE;

ALTER TABLE crm_lead ADD COLUMN IF NOT EXISTS name VARCHAR(256);
ALTER TABLE crm_lead ADD COLUMN IF NOT EXISTS type VARCHAR(16);
ALTER TABLE crm_lead ADD COLUMN IF NOT EXISTS priority VARCHAR(16);
ALTER TABLE crm_lead ADD COLUMN IF NOT EXISTS partner_id INTEGER;
ALTER TABLE crm_lead ADD COLUMN IF NOT EXISTS user_id INTEGER;
ALTER TABLE crm_lead ADD COLUMN IF NOT EXISTS company_id INTEGER;
ALTER TABLE crm_lead ADD COLUMN IF NOT EXISTS expected_revenue NUMERIC(19,2);
ALTER TABLE crm_lead ADD COLUMN IF NOT EXISTS probability NUMERIC(5,2);
ALTER TABLE crm_lead ADD COLUMN IF NOT EXISTS stage_id INTEGER;
ALTER TABLE crm_lead ADD COLUMN IF NOT EXISTS email_from VARCHAR(256);
ALTER TABLE crm_lead ADD COLUMN IF NOT EXISTS phone VARCHAR(64);
ALTER TABLE crm_lead ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE crm_lead ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT TRUE;

UPDATE crm_stage
SET name = COALESCE(name, CONCAT('CRM-STAGE-', id::text))
WHERE name IS NULL;

UPDATE crm_lead
SET name = COALESCE(name, CONCAT('CRM-LEAD-', id::text))
WHERE name IS NULL;

-- HR
ALTER TABLE hr_department ADD COLUMN IF NOT EXISTS name VARCHAR(128);
ALTER TABLE hr_department ADD COLUMN IF NOT EXISTS parent_id INTEGER;
ALTER TABLE hr_department ADD COLUMN IF NOT EXISTS manager_id INTEGER;
ALTER TABLE hr_department ADD COLUMN IF NOT EXISTS company_id INTEGER;

ALTER TABLE hr_employee ADD COLUMN IF NOT EXISTS name VARCHAR(128);
ALTER TABLE hr_employee ADD COLUMN IF NOT EXISTS job_id INTEGER;
ALTER TABLE hr_employee ADD COLUMN IF NOT EXISTS department_id INTEGER;
ALTER TABLE hr_employee ADD COLUMN IF NOT EXISTS parent_id INTEGER;
ALTER TABLE hr_employee ADD COLUMN IF NOT EXISTS user_id INTEGER;
ALTER TABLE hr_employee ADD COLUMN IF NOT EXISTS company_id INTEGER;
ALTER TABLE hr_employee ADD COLUMN IF NOT EXISTS work_email VARCHAR(128);
ALTER TABLE hr_employee ADD COLUMN IF NOT EXISTS work_phone VARCHAR(64);
ALTER TABLE hr_employee ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT TRUE;

ALTER TABLE hr_job ADD COLUMN IF NOT EXISTS name VARCHAR(128);
ALTER TABLE hr_job ADD COLUMN IF NOT EXISTS department_id INTEGER;
ALTER TABLE hr_job ADD COLUMN IF NOT EXISTS no_of_employee INTEGER;
ALTER TABLE hr_job ADD COLUMN IF NOT EXISTS company_id INTEGER;

ALTER TABLE hr_leave ADD COLUMN IF NOT EXISTS name VARCHAR(256);
ALTER TABLE hr_leave ADD COLUMN IF NOT EXISTS employee_id INTEGER;
ALTER TABLE hr_leave ADD COLUMN IF NOT EXISTS holiday_status_id INTEGER;
ALTER TABLE hr_leave ADD COLUMN IF NOT EXISTS date_from TIMESTAMP;
ALTER TABLE hr_leave ADD COLUMN IF NOT EXISTS date_to TIMESTAMP;
ALTER TABLE hr_leave ADD COLUMN IF NOT EXISTS number_of_days NUMERIC(5,2);
ALTER TABLE hr_leave ADD COLUMN IF NOT EXISTS state VARCHAR(16);

ALTER TABLE hr_attendance ADD COLUMN IF NOT EXISTS name VARCHAR(256);
ALTER TABLE hr_attendance ADD COLUMN IF NOT EXISTS employee_id INTEGER;
ALTER TABLE hr_attendance ADD COLUMN IF NOT EXISTS check_in TIMESTAMP;
ALTER TABLE hr_attendance ADD COLUMN IF NOT EXISTS check_out TIMESTAMP;
ALTER TABLE hr_attendance ADD COLUMN IF NOT EXISTS worked_hours NUMERIC(10,2);

UPDATE hr_department
SET name = COALESCE(name, CONCAT('HR-DEPT-', id::text))
WHERE name IS NULL;

UPDATE hr_employee
SET name = COALESCE(name, CONCAT('HR-EMP-', id::text))
WHERE name IS NULL;

UPDATE hr_job
SET name = COALESCE(name, CONCAT('HR-JOB-', id::text))
WHERE name IS NULL;

UPDATE hr_leave
SET name = COALESCE(name, CONCAT('HR-LEAVE-', id::text)),
    state = COALESCE(state, 'draft')
WHERE name IS NULL OR state IS NULL;

UPDATE hr_attendance
SET name = COALESCE(name, CONCAT('HR-ATT-', id::text))
WHERE name IS NULL;

-- Attachments
ALTER TABLE ir_attachment ADD COLUMN IF NOT EXISTS name VARCHAR(256);
ALTER TABLE ir_attachment ADD COLUMN IF NOT EXISTS res_model VARCHAR(128);
ALTER TABLE ir_attachment ADD COLUMN IF NOT EXISTS res_id INTEGER;
ALTER TABLE ir_attachment ADD COLUMN IF NOT EXISTS datas BYTEA;
ALTER TABLE ir_attachment ADD COLUMN IF NOT EXISTS mimetype VARCHAR(128);

UPDATE ir_attachment
SET name = COALESCE(name, CONCAT('ATT-', id::text))
WHERE name IS NULL;

-- Projects
ALTER TABLE project_project ADD COLUMN IF NOT EXISTS name VARCHAR(256);
ALTER TABLE project_project ADD COLUMN IF NOT EXISTS user_id INTEGER;
ALTER TABLE project_project ADD COLUMN IF NOT EXISTS partner_id INTEGER;
ALTER TABLE project_project ADD COLUMN IF NOT EXISTS company_id INTEGER;
ALTER TABLE project_project ADD COLUMN IF NOT EXISTS date_start DATE;
ALTER TABLE project_project ADD COLUMN IF NOT EXISTS date TIMESTAMP;
ALTER TABLE project_project ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT TRUE;

ALTER TABLE project_task ADD COLUMN IF NOT EXISTS name VARCHAR(256);
ALTER TABLE project_task ADD COLUMN IF NOT EXISTS project_id INTEGER;
ALTER TABLE project_task ADD COLUMN IF NOT EXISTS user_id INTEGER;
ALTER TABLE project_task ADD COLUMN IF NOT EXISTS company_id INTEGER;
ALTER TABLE project_task ADD COLUMN IF NOT EXISTS date_deadline DATE;
ALTER TABLE project_task ADD COLUMN IF NOT EXISTS stage_id INTEGER;
ALTER TABLE project_task ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE project_task ADD COLUMN IF NOT EXISTS sequence INTEGER;

UPDATE project_project
SET name = COALESCE(name, CONCAT('PROJECT-', id::text))
WHERE name IS NULL;

UPDATE project_task
SET name = COALESCE(name, CONCAT('TASK-', id::text))
WHERE name IS NULL;

