import type { ModuleKey } from '@/config/module-manifest'

export type WorkbenchShortcutTone = 'default' | 'success' | 'warning' | 'danger' | 'info'
export type WorkbenchShortcutButtonType = 'default' | 'primary' | 'success' | 'warning' | 'info' | 'danger'
export type WorkbenchShortcutActionKey =
  | 'open-create'
  | 'open-section'
  | 'open-route'
  | 'open-cutover'
  | 'open-gates'
  | 'open-closed-loop'
  | 'open-guardrail'
  | 'open-settlement'
  | 'open-top-risk'
  | 'open-top-risk-documents'
  | 'open-top-risk-timeline'
  | 'open-financial-trace'
  | 'export-exceptions'
  | 'export-exception-packet'
  | 'export-trace-bundle'
  | 'export-top-trace'
  | 'export-rollback-drill'
  | 'export-handbook'

export interface WorkbenchShortcutItem {
  key: string
  title: string
  description: string
  meta?: string
  tone?: WorkbenchShortcutTone
  buttonLabel: string
  buttonType?: WorkbenchShortcutButtonType
  actionKey: WorkbenchShortcutActionKey
  routeName?: string
  query?: Record<string, string | undefined>
  section?: string
}

function saleOrderShortcuts(isEnglish: boolean): WorkbenchShortcutItem[] {
  return isEnglish
    ? [
        {
          key: 'sale-create',
          title: 'New Sales Draft',
          description: 'Open a new sales draft directly from the workbench before operators drift into downstream execution.',
          meta: 'saleOrder.create',
          tone: 'success',
          buttonLabel: 'Create Draft',
          buttonType: 'primary',
          actionKey: 'open-create',
        },
        {
          key: 'sale-delivery',
          title: 'Delivery Execution Desk',
          description: 'Jump into downstream transfers from the sales chain without rebuilding customer or origin context.',
          meta: 'saleOrder -> stockPicking',
          tone: 'warning',
          buttonLabel: 'Open Transfers',
          buttonType: 'warning',
          actionKey: 'open-route',
          routeName: 'stockPicking',
          query: { relatedTo: 'saleOrder', section: 'ops-execution-feedback' },
        },
        {
          key: 'sale-invoice',
          title: 'Billing Follow-up Desk',
          description: 'Continue into invoice review from the same chain instead of restarting inside accounting search.',
          meta: 'saleOrder -> accountInvoice',
          tone: 'warning',
          buttonLabel: 'Open Invoices',
          buttonType: 'warning',
          actionKey: 'open-route',
          routeName: 'accountInvoice',
          query: { relatedTo: 'saleOrder', section: 'ops-settlement' },
        },
        {
          key: 'sale-trace',
          title: 'Sales Trace Repair',
          description: 'Open the active top-risk sales trace so source continuity, artifacts, and evidence can be repaired immediately.',
          meta: 'Top risk · traceability',
          tone: 'danger',
          buttonLabel: 'Open Trace',
          buttonType: 'danger',
          actionKey: 'open-financial-trace',
        },
        {
          key: 'sale-docs',
          title: 'Quotation / Contract Evidence',
          description: 'Go straight to the document area for the current risk record and keep quotations, contracts, and support files together.',
          meta: 'Documents / attachments',
          tone: 'info',
          buttonLabel: 'Open Documents',
          buttonType: 'info',
          actionKey: 'open-top-risk-documents',
        },
        {
          key: 'sale-rollback',
          title: 'Freeze Sales Rollback Pack',
          description: 'Export the current rollback drill packet before the sales pilot widens and more delivery artifacts are generated.',
          meta: 'Rollback packet',
          tone: 'success',
          buttonLabel: 'Export Drill',
          buttonType: 'success',
          actionKey: 'export-rollback-drill',
        },
      ]
    : [
        {
          key: 'sale-create',
          title: '新建销售草稿',
          description: '直接从工作台打开新的销售草稿，避免操作员先漂移到下游执行界面。',
          meta: 'saleOrder.create',
          tone: 'success',
          buttonLabel: '新建草稿',
          buttonType: 'primary',
          actionKey: 'open-create',
        },
        {
          key: 'sale-delivery',
          title: '出库执行台',
          description: '不重建客户或来源上下文，直接从销售链跳进下游调拨执行。',
          meta: 'saleOrder -> stockPicking',
          tone: 'warning',
          buttonLabel: '打开调拨',
          buttonType: 'warning',
          actionKey: 'open-route',
          routeName: 'stockPicking',
          query: { relatedTo: 'saleOrder', section: 'ops-execution-feedback' },
        },
        {
          key: 'sale-invoice',
          title: '开票跟进台',
          description: '继续沿同一条链进入发票审查，而不是回到会计搜索里重新找单。',
          meta: 'saleOrder -> accountInvoice',
          tone: 'warning',
          buttonLabel: '打开发票',
          buttonType: 'warning',
          actionKey: 'open-route',
          routeName: 'accountInvoice',
          query: { relatedTo: 'saleOrder', section: 'ops-settlement' },
        },
        {
          key: 'sale-trace',
          title: '销售追溯修补',
          description: '直接打开当前最高风险销售追溯记录，立刻补来源连续性、结果对象和证据。',
          meta: '最高风险 · traceability',
          tone: 'danger',
          buttonLabel: '打开追溯',
          buttonType: 'danger',
          actionKey: 'open-financial-trace',
        },
        {
          key: 'sale-docs',
          title: '报价/合同证据',
          description: '直达当前风险记录的文档区，把报价、合同和支撑文件固定在同一处。',
          meta: 'Documents / attachments',
          tone: 'info',
          buttonLabel: '打开文档',
          buttonType: 'info',
          actionKey: 'open-top-risk-documents',
        },
        {
          key: 'sale-rollback',
          title: '冻结销售回退包',
          description: '在销售试点继续放量前，先导出当前回退演练包。',
          meta: '回退演练包',
          tone: 'success',
          buttonLabel: '导出演练包',
          buttonType: 'success',
          actionKey: 'export-rollback-drill',
        },
      ]
}

function purchaseOrderShortcuts(isEnglish: boolean): WorkbenchShortcutItem[] {
  return isEnglish
    ? [
        {
          key: 'purchase-create',
          title: 'New Procurement Draft',
          description: 'Open a new purchase draft directly from the procurement cockpit before operators move into receipt or billing follow-up.',
          meta: 'purchaseOrder.create',
          tone: 'success',
          buttonLabel: 'Create Draft',
          buttonType: 'primary',
          actionKey: 'open-create',
        },
        {
          key: 'purchase-receipt',
          title: 'Receipt Execution Desk',
          description: 'Open downstream receipt execution so quantities, routes, and receiving pressure stay in the same procurement path.',
          meta: 'purchaseOrder -> stockPicking',
          tone: 'warning',
          buttonLabel: 'Open Receipts',
          buttonType: 'warning',
          actionKey: 'open-route',
          routeName: 'stockPicking',
          query: { relatedTo: 'purchaseOrder', section: 'ops-execution-feedback' },
        },
        {
          key: 'purchase-bill',
          title: 'Bill Review Desk',
          description: 'Jump directly into billing follow-up from the purchase workbench instead of rebuilding bill context by search.',
          meta: 'purchaseOrder -> accountInvoice',
          tone: 'warning',
          buttonLabel: 'Open Bills',
          buttonType: 'warning',
          actionKey: 'open-route',
          routeName: 'accountInvoice',
          query: { relatedTo: 'purchaseOrder', section: 'ops-settlement' },
        },
        {
          key: 'purchase-payment',
          title: 'Vendor Payment Desk',
          description: 'Continue from the procurement chain into vendor payment closure without losing the originating order context.',
          meta: 'purchaseOrder -> accountPayment',
          tone: 'info',
          buttonLabel: 'Open Payments',
          buttonType: 'info',
          actionKey: 'open-route',
          routeName: 'accountPayment',
          query: { relatedTo: 'purchaseOrder', section: 'ops-payment-linkage' },
        },
        {
          key: 'purchase-docs',
          title: 'Vendor Evidence Desk',
          description: 'Go to the current top-risk document area and keep supplier attachments, contracts, and receipt proofs together.',
          meta: 'Vendor evidence',
          tone: 'info',
          buttonLabel: 'Open Documents',
          buttonType: 'info',
          actionKey: 'open-top-risk-documents',
        },
        {
          key: 'purchase-bundle',
          title: 'Freeze Procurement Trace Bundle',
          description: 'Export the current procurement trace bundle so receipt, bill, and payment references stay packaged together.',
          meta: 'Trace bundle',
          tone: 'success',
          buttonLabel: 'Export Bundle',
          buttonType: 'success',
          actionKey: 'export-trace-bundle',
        },
      ]
    : [
        {
          key: 'purchase-create',
          title: '新建采购草稿',
          description: '直接从采购驾驶舱打开新的采购草稿，避免先切去收货或账单跟进。',
          meta: 'purchaseOrder.create',
          tone: 'success',
          buttonLabel: '新建草稿',
          buttonType: 'primary',
          actionKey: 'open-create',
        },
        {
          key: 'purchase-receipt',
          title: '收货执行台',
          description: '直接打开下游收货执行，让数量、路线和收货压力留在同一采购路径里。',
          meta: 'purchaseOrder -> stockPicking',
          tone: 'warning',
          buttonLabel: '打开收货',
          buttonType: 'warning',
          actionKey: 'open-route',
          routeName: 'stockPicking',
          query: { relatedTo: 'purchaseOrder', section: 'ops-execution-feedback' },
        },
        {
          key: 'purchase-bill',
          title: '账单审查台',
          description: '从采购工作台直接跳到账单跟进，不再靠搜索去重建账单上下文。',
          meta: 'purchaseOrder -> accountInvoice',
          tone: 'warning',
          buttonLabel: '打开账单',
          buttonType: 'warning',
          actionKey: 'open-route',
          routeName: 'accountInvoice',
          query: { relatedTo: 'purchaseOrder', section: 'ops-settlement' },
        },
        {
          key: 'purchase-payment',
          title: '供应商付款台',
          description: '沿采购链继续进入供应商付款闭环，同时保留源采购单上下文。',
          meta: 'purchaseOrder -> accountPayment',
          tone: 'info',
          buttonLabel: '打开付款',
          buttonType: 'info',
          actionKey: 'open-route',
          routeName: 'accountPayment',
          query: { relatedTo: 'purchaseOrder', section: 'ops-payment-linkage' },
        },
        {
          key: 'purchase-docs',
          title: '供应商证据台',
          description: '直达当前最高风险记录的文档区，把供应商附件、合同和收货证明放在一起。',
          meta: '供应商证据',
          tone: 'info',
          buttonLabel: '打开文档',
          buttonType: 'info',
          actionKey: 'open-top-risk-documents',
        },
        {
          key: 'purchase-bundle',
          title: '冻结采购追溯包',
          description: '导出当前采购追溯证据包，把收货、账单和付款引用固定打包。',
          meta: '追溯证据包',
          tone: 'success',
          buttonLabel: '导出证据包',
          buttonType: 'success',
          actionKey: 'export-trace-bundle',
        },
      ]
}

function stockPickingShortcuts(isEnglish: boolean): WorkbenchShortcutItem[] {
  return isEnglish
    ? [
        {
          key: 'picking-execution-feedback',
          title: 'Execution Feedback Desk',
          description: 'Open the shared execution cockpit so transfer progress, move completion, and warehouse pressure stay visible together.',
          meta: 'Execution / feedback',
          tone: 'danger',
          buttonLabel: 'Open Execution',
          buttonType: 'danger',
          actionKey: 'open-section',
          section: 'ops-execution-feedback',
        },
        {
          key: 'picking-quant-impact',
          title: 'Quant Impact Desk',
          description: 'Open the shared quant impact desk to inspect touched locations, stock pressure, and rollback-sensitive transfers.',
          meta: 'Quant / rollback review',
          tone: 'warning',
          buttonLabel: 'Open Quant Desk',
          buttonType: 'warning',
          actionKey: 'open-section',
          section: 'ops-quant-impact',
        },
        {
          key: 'picking-create',
          title: 'New Transfer Draft',
          description: 'Create a new transfer draft directly from the execution surface when a pilot handoff needs manual warehouse action.',
          meta: 'stockPicking.create',
          tone: 'success',
          buttonLabel: 'Create Transfer',
          buttonType: 'primary',
          actionKey: 'open-create',
        },
        {
          key: 'picking-trace',
          title: 'Validation Trace Desk',
          description: 'Open the current transfer trace desk before validation so route, moves, and evidence remain explainable.',
          meta: 'Validate / traceability',
          tone: 'danger',
          buttonLabel: 'Open Trace',
          buttonType: 'danger',
          actionKey: 'open-financial-trace',
        },
        {
          key: 'picking-docs',
          title: 'Execution Evidence Desk',
          description: 'Go straight to the transfer document zone to keep packing proof, receipts, and handling evidence on the same record.',
          meta: 'Packing / proof files',
          tone: 'warning',
          buttonLabel: 'Open Documents',
          buttonType: 'warning',
          actionKey: 'open-top-risk-documents',
        },
        {
          key: 'picking-timeline',
          title: 'Execution Timeline Desk',
          description: 'Open the transfer timeline and review validation notes, exception chatter, and warehouse handoff memory.',
          meta: 'Timeline / warehouse memory',
          tone: 'info',
          buttonLabel: 'Open Timeline',
          buttonType: 'info',
          actionKey: 'open-top-risk-timeline',
        },
        {
          key: 'picking-sales',
          title: 'Return To Sales Origin',
          description: 'Jump back to the upstream sales workspace when the transfer origin, customer scope, or delivery promise must be rechecked.',
          meta: 'stockPicking -> saleOrder',
          tone: 'info',
          buttonLabel: 'Open Sales',
          buttonType: 'info',
          actionKey: 'open-route',
          routeName: 'saleOrder',
          query: { relatedTo: 'stockPicking', section: 'ops-financial-trace' },
        },
        {
          key: 'picking-rollback',
          title: 'Freeze Transfer Rollback Pack',
          description: 'Export the rollback drill pack so route, move, and quant rollback review can be rehearsed before the pilot widens.',
          meta: 'Rollback / quant safety',
          tone: 'success',
          buttonLabel: 'Export Drill',
          buttonType: 'success',
          actionKey: 'export-rollback-drill',
        },
      ]
    : [
        {
          key: 'picking-execution-feedback',
          title: '执行反馈台',
          description: '打开共享执行驾驶舱，把调拨进度、移动完成度和仓储压力放在一起看。',
          meta: 'Execution / feedback',
          tone: 'danger',
          buttonLabel: '打开执行台',
          buttonType: 'danger',
          actionKey: 'open-section',
          section: 'ops-execution-feedback',
        },
        {
          key: 'picking-quant-impact',
          title: '库存影响台',
          description: '打开共享库存影响台，统一核对涉及库位、库存压力和回退敏感调拨。',
          meta: 'Quant / rollback review',
          tone: 'warning',
          buttonLabel: '打开库存影响台',
          buttonType: 'warning',
          actionKey: 'open-section',
          section: 'ops-quant-impact',
        },
        {
          key: 'picking-create',
          title: '新建调拨草稿',
          description: '当试点交接需要人工仓储动作时，直接从执行界面新建调拨草稿。',
          meta: 'stockPicking.create',
          tone: 'success',
          buttonLabel: '新建调拨',
          buttonType: 'primary',
          actionKey: 'open-create',
        },
        {
          key: 'picking-trace',
          title: '校验追溯台',
          description: '在 Validate 之前先打开调拨追溯台，让路线、移动行和证据都可解释。',
          meta: 'Validate / traceability',
          tone: 'danger',
          buttonLabel: '打开追溯',
          buttonType: 'danger',
          actionKey: 'open-financial-trace',
        },
        {
          key: 'picking-docs',
          title: '执行证据台',
          description: '直达调拨文档区，把装箱证明、签收凭据和执行附件留在同一条记录上。',
          meta: '装箱 / 证明文件',
          tone: 'warning',
          buttonLabel: '打开文档',
          buttonType: 'warning',
          actionKey: 'open-top-risk-documents',
        },
        {
          key: 'picking-timeline',
          title: '执行时间轴台',
          description: '打开调拨时间轴，审查校验备注、异常沟通和仓储交接记忆。',
          meta: 'Timeline / warehouse memory',
          tone: 'info',
          buttonLabel: '打开时间轴',
          buttonType: 'info',
          actionKey: 'open-top-risk-timeline',
        },
        {
          key: 'picking-sales',
          title: '返回销售来源',
          description: '当调拨来源、客户范围或交付承诺要重新核对时，直接跳回上游销售工作台。',
          meta: 'stockPicking -> saleOrder',
          tone: 'info',
          buttonLabel: '打开销售',
          buttonType: 'info',
          actionKey: 'open-route',
          routeName: 'saleOrder',
          query: { relatedTo: 'stockPicking', section: 'ops-financial-trace' },
        },
        {
          key: 'picking-rollback',
          title: '冻结调拨回退包',
          description: '导出回退演练包，让路线、move 和 quant 回退核对在放量前先完成演练。',
          meta: '回退 / quant 安全',
          tone: 'success',
          buttonLabel: '导出演练包',
          buttonType: 'success',
          actionKey: 'export-rollback-drill',
        },
      ]
}

function accountInvoiceShortcuts(isEnglish: boolean): WorkbenchShortcutItem[] {
  return isEnglish
    ? [
        {
          key: 'invoice-linkage',
          title: 'Payment Linkage Desk',
          description: 'Open the linkage desk and review invoice anchors, payment artifacts, and journal refs together.',
          meta: 'Invoice / payment / journal',
          tone: 'warning',
          buttonLabel: 'Open Linkage',
          buttonType: 'warning',
          actionKey: 'open-section',
          section: 'ops-payment-linkage',
        },
        {
          key: 'invoice-create',
          title: 'New Invoice Draft',
          description: 'Open a fresh invoice draft directly from the billing workbench before moving into payment or posting follow-up.',
          meta: 'accountInvoice.create',
          tone: 'success',
          buttonLabel: 'Create Invoice',
          buttonType: 'primary',
          actionKey: 'open-create',
        },
        {
          key: 'invoice-payments',
          title: 'Payment Registration Desk',
          description: 'Jump into payment handling from the invoice shell so settlement does not fragment across separate searches.',
          meta: 'accountInvoice -> accountPayment',
          tone: 'warning',
          buttonLabel: 'Open Payments',
          buttonType: 'warning',
          actionKey: 'open-route',
          routeName: 'accountPayment',
          query: { relatedTo: 'accountInvoice', section: 'ops-payment-linkage' },
        },
        {
          key: 'invoice-settlement',
          title: 'Settlement Closure Desk',
          description: 'Open the settlement trace route and repair missing origin, due-date, or payment continuity first.',
          meta: 'Settlement / traceability',
          tone: 'danger',
          buttonLabel: 'Open Settlement',
          buttonType: 'danger',
          actionKey: 'open-section',
          section: 'ops-settlement',
        },
        {
          key: 'invoice-docs',
          title: 'Invoice Evidence Desk',
          description: 'Go directly to invoice documents and keep PDFs, approval files, and support proof attached before handoff.',
          meta: 'PDF / attachments',
          tone: 'info',
          buttonLabel: 'Open Documents',
          buttonType: 'info',
          actionKey: 'open-top-risk-documents',
        },
        {
          key: 'invoice-bundle',
          title: 'Freeze Billing Trace Bundle',
          description: 'Export the current invoice trace bundle so source, payment, and evidence continuity can be reviewed together.',
          meta: 'Trace bundle',
          tone: 'success',
          buttonLabel: 'Export Bundle',
          buttonType: 'success',
          actionKey: 'export-trace-bundle',
        },
        {
          key: 'invoice-guardrail',
          title: 'Billing Guardrail Desk',
          description: 'Open billing guardrails and keep invoice posting, cancellation, and payment linkage protected before pilot expansion.',
          meta: 'before_save / before_action',
          tone: 'info',
          buttonLabel: 'Open Guardrails',
          buttonType: 'info',
          actionKey: 'open-guardrail',
        },
      ]
    : [
        {
          key: 'invoice-linkage',
          title: '付款联动台',
          description: '打开联动台，把发票锚点、付款结果对象和凭证引用放在一起复核。',
          meta: 'Invoice / payment / journal',
          tone: 'warning',
          buttonLabel: '打开联动台',
          buttonType: 'warning',
          actionKey: 'open-section',
          section: 'ops-payment-linkage',
        },
        {
          key: 'invoice-create',
          title: '新建发票草稿',
          description: '直接从账单工作台打开新的发票草稿，再继续付款或过账跟进。',
          meta: 'accountInvoice.create',
          tone: 'success',
          buttonLabel: '新建发票',
          buttonType: 'primary',
          actionKey: 'open-create',
        },
        {
          key: 'invoice-payments',
          title: '付款登记台',
          description: '从发票壳层直接跳入付款处理，让结算不再碎裂到不同搜索页面。',
          meta: 'accountInvoice -> accountPayment',
          tone: 'warning',
          buttonLabel: '打开付款',
          buttonType: 'warning',
          actionKey: 'open-route',
          routeName: 'accountPayment',
          query: { relatedTo: 'accountInvoice', section: 'ops-payment-linkage' },
        },
        {
          key: 'invoice-settlement',
          title: '结算闭环台',
          description: '直接打开面向结算的追溯路径，优先补来源、到期日和付款连续性。',
          meta: 'Settlement / traceability',
          tone: 'danger',
          buttonLabel: '打开结算',
          buttonType: 'danger',
          actionKey: 'open-section',
          section: 'ops-settlement',
        },
        {
          key: 'invoice-docs',
          title: '发票证据台',
          description: '直达发票文档区，把 PDF、审批文件和支撑证明在交接前固定挂好。',
          meta: 'PDF / attachments',
          tone: 'info',
          buttonLabel: '打开文档',
          buttonType: 'info',
          actionKey: 'open-top-risk-documents',
        },
        {
          key: 'invoice-bundle',
          title: '冻结账单追溯包',
          description: '导出当前发票追溯证据包，把来源、付款和证据连续性一起打包审查。',
          meta: '追溯证据包',
          tone: 'success',
          buttonLabel: '导出证据包',
          buttonType: 'success',
          actionKey: 'export-trace-bundle',
        },
        {
          key: 'invoice-guardrail',
          title: '账单 Guardrail 台',
          description: '打开账单 Guardrail，持续保护发票过账、取消和付款链接。',
          meta: 'before_save / before_action',
          tone: 'info',
          buttonLabel: '打开规则台',
          buttonType: 'info',
          actionKey: 'open-guardrail',
        },
      ]
}

function accountPaymentShortcuts(isEnglish: boolean): WorkbenchShortcutItem[] {
  return isEnglish
    ? [
        {
          key: 'payment-linkage',
          title: 'Payment Linkage Desk',
          description: 'Open the linkage desk and keep source invoice anchors plus journal refs visible from the payment shell.',
          meta: 'Payment / invoice / journal',
          tone: 'warning',
          buttonLabel: 'Open Linkage',
          buttonType: 'warning',
          actionKey: 'open-section',
          section: 'ops-payment-linkage',
        },
        {
          key: 'payment-create',
          title: 'New Payment Draft',
          description: 'Open a new payment draft directly from the payment shell before switching to invoice or journal review.',
          meta: 'accountPayment.create',
          tone: 'success',
          buttonLabel: 'Create Payment',
          buttonType: 'primary',
          actionKey: 'open-create',
        },
        {
          key: 'payment-source',
          title: 'Source Invoice Desk',
          description: 'Return to source invoices quickly so payment amount, partner, and settlement intent stay grounded in the business document.',
          meta: 'accountPayment -> accountInvoice',
          tone: 'warning',
          buttonLabel: 'Open Invoices',
          buttonType: 'warning',
          actionKey: 'open-route',
          routeName: 'accountInvoice',
          query: { relatedTo: 'accountPayment', section: 'ops-payment-linkage' },
        },
        {
          key: 'payment-journal',
          title: 'Journal Review Desk',
          description: 'Jump to generated journal entries and keep payment posting review inside the same closure route.',
          meta: 'accountPayment -> accountMove',
          tone: 'warning',
          buttonLabel: 'Open Journal',
          buttonType: 'warning',
          actionKey: 'open-route',
          routeName: 'accountMove',
          query: { relatedTo: 'accountPayment', section: 'ops-settlement' },
        },
        {
          key: 'payment-settlement',
          title: 'Settlement Trace Desk',
          description: 'Open the payment settlement trace first when source anchor, journal continuity, or evidence is still weak.',
          meta: 'Settlement / journal trace',
          tone: 'danger',
          buttonLabel: 'Open Trace',
          buttonType: 'danger',
          actionKey: 'open-section',
          section: 'ops-settlement',
        },
        {
          key: 'payment-docs',
          title: 'Bank Proof Desk',
          description: 'Go straight to payment documents and keep bank proof, receipts, and settlement attachments tied to the payment record.',
          meta: 'Bank proof / attachments',
          tone: 'info',
          buttonLabel: 'Open Documents',
          buttonType: 'info',
          actionKey: 'open-top-risk-documents',
        },
        {
          key: 'payment-top-trace',
          title: 'Freeze Top Payment Trace',
          description: 'Export the current top-risk payment trace packet before more payment postings accumulate inside the pilot.',
          meta: 'Top trace packet',
          tone: 'success',
          buttonLabel: 'Export Top Trace',
          buttonType: 'success',
          actionKey: 'export-top-trace',
        },
      ]
    : [
        {
          key: 'payment-linkage',
          title: '付款联动台',
          description: '打开联动台，把源发票锚点和凭证引用固定在付款壳层里。',
          meta: 'Payment / invoice / journal',
          tone: 'warning',
          buttonLabel: '打开联动台',
          buttonType: 'warning',
          actionKey: 'open-section',
          section: 'ops-payment-linkage',
        },
        {
          key: 'payment-create',
          title: '新建付款草稿',
          description: '直接从付款壳层打开新的付款草稿，再继续发票或凭证审查。',
          meta: 'accountPayment.create',
          tone: 'success',
          buttonLabel: '新建付款',
          buttonType: 'primary',
          actionKey: 'open-create',
        },
        {
          key: 'payment-source',
          title: '源发票工作台',
          description: '快速返回源发票，让付款金额、伙伴和结算意图继续扎根在业务单据里。',
          meta: 'accountPayment -> accountInvoice',
          tone: 'warning',
          buttonLabel: '打开发票',
          buttonType: 'warning',
          actionKey: 'open-route',
          routeName: 'accountInvoice',
          query: { relatedTo: 'accountPayment', section: 'ops-payment-linkage' },
        },
        {
          key: 'payment-journal',
          title: '凭证审查台',
          description: '跳到已生成凭证，让付款过账复核继续留在同一闭环路径中。',
          meta: 'accountPayment -> accountMove',
          tone: 'warning',
          buttonLabel: '打开凭证',
          buttonType: 'warning',
          actionKey: 'open-route',
          routeName: 'accountMove',
          query: { relatedTo: 'accountPayment', section: 'ops-settlement' },
        },
        {
          key: 'payment-settlement',
          title: '结算追溯台',
          description: '当来源锚点、凭证连续性或证据仍然薄弱时，先打开付款结算追溯台。',
          meta: 'Settlement / journal trace',
          tone: 'danger',
          buttonLabel: '打开追溯',
          buttonType: 'danger',
          actionKey: 'open-section',
          section: 'ops-settlement',
        },
        {
          key: 'payment-docs',
          title: '银行凭证台',
          description: '直达付款文档区，把银行回单、收据和结算附件挂在同一付款记录上。',
          meta: 'Bank proof / attachments',
          tone: 'info',
          buttonLabel: '打开文档',
          buttonType: 'info',
          actionKey: 'open-top-risk-documents',
        },
        {
          key: 'payment-top-trace',
          title: '冻结付款最高追溯包',
          description: '在试点里继续积累更多付款过账前，先导出当前最高风险付款追溯包。',
          meta: '最高追溯包',
          tone: 'success',
          buttonLabel: '导出最高追溯包',
          buttonType: 'success',
          actionKey: 'export-top-trace',
        },
      ]
}

function resPartnerShortcuts(isEnglish: boolean): WorkbenchShortcutItem[] {
  return isEnglish
    ? [
        {
          key: 'partner-create',
          title: 'New Partner Draft',
          description: 'Open a new shared partner draft directly from the master-data workbench before downstream sales or procurement begins.',
          meta: 'resPartner.create',
          tone: 'success',
          buttonLabel: 'Create Partner',
          buttonType: 'primary',
          actionKey: 'open-create',
        },
        {
          key: 'partner-evidence',
          title: 'Partner Evidence Desk',
          description: 'Open the evidence lane and keep contracts, certificates, and onboarding files attached before the partner enters live use.',
          meta: 'Evidence / onboarding',
          tone: 'warning',
          buttonLabel: 'Open Evidence',
          buttonType: 'warning',
          actionKey: 'open-section',
          section: 'ops-evidence',
        },
        {
          key: 'partner-gates',
          title: 'Master Data Gate Desk',
          description: 'Open the gate desk and check smoke, workbench, traceability, and rollback readiness before widening pilot usage.',
          meta: 'Acceptance gates',
          tone: 'warning',
          buttonLabel: 'Open Gates',
          buttonType: 'warning',
          actionKey: 'open-gates',
        },
        {
          key: 'partner-sales',
          title: 'Customer Chain Workbench',
          description: 'Jump into the sales workbench with partner context preserved when customer-side pilot flow needs to continue.',
          meta: 'resPartner -> saleOrder',
          tone: 'info',
          buttonLabel: 'Open Sales',
          buttonType: 'info',
          actionKey: 'open-route',
          routeName: 'saleOrder',
          query: { relatedTo: 'resPartner', section: 'ops-financial-trace' },
        },
        {
          key: 'partner-purchase',
          title: 'Vendor Chain Workbench',
          description: 'Jump into the purchase workbench with partner context preserved when vendor-side pilot flow needs to continue.',
          meta: 'resPartner -> purchaseOrder',
          tone: 'info',
          buttonLabel: 'Open Purchase',
          buttonType: 'info',
          actionKey: 'open-route',
          routeName: 'purchaseOrder',
          query: { relatedTo: 'resPartner', section: 'ops-financial-trace' },
        },
        {
          key: 'partner-exception-packet',
          title: 'Freeze Partner Exception Packet',
          description: 'Export the current partner exception packet so identity, contact, and evidence gaps stay visible during handoff.',
          meta: 'Exception packet',
          tone: 'success',
          buttonLabel: 'Export Packet',
          buttonType: 'success',
          actionKey: 'export-exception-packet',
        },
      ]
    : [
        {
          key: 'partner-create',
          title: '新建伙伴草稿',
          description: '直接从主数据工作台打开新的共享伙伴草稿，再继续销售或采购下游流程。',
          meta: 'resPartner.create',
          tone: 'success',
          buttonLabel: '新建伙伴',
          buttonType: 'primary',
          actionKey: 'open-create',
        },
        {
          key: 'partner-evidence',
          title: '伙伴证据台',
          description: '打开证据工作区，在伙伴进入真实使用前先挂好合同、证照和准入文件。',
          meta: '证据 / 准入',
          tone: 'warning',
          buttonLabel: '打开证据台',
          buttonType: 'warning',
          actionKey: 'open-section',
          section: 'ops-evidence',
        },
        {
          key: 'partner-gates',
          title: '主数据门槛台',
          description: '打开门槛台，先核 smoke、工作台、追溯和回退准备度，再扩大试点使用。',
          meta: '放行门槛',
          tone: 'warning',
          buttonLabel: '打开门槛台',
          buttonType: 'warning',
          actionKey: 'open-gates',
        },
        {
          key: 'partner-sales',
          title: '客户链工作台',
          description: '在保留伙伴上下文的前提下直接进入销售工作台，继续客户侧试点流转。',
          meta: 'resPartner -> saleOrder',
          tone: 'info',
          buttonLabel: '打开销售',
          buttonType: 'info',
          actionKey: 'open-route',
          routeName: 'saleOrder',
          query: { relatedTo: 'resPartner', section: 'ops-financial-trace' },
        },
        {
          key: 'partner-purchase',
          title: '供应商链工作台',
          description: '在保留伙伴上下文的前提下直接进入采购工作台，继续供应商侧试点流转。',
          meta: 'resPartner -> purchaseOrder',
          tone: 'info',
          buttonLabel: '打开采购',
          buttonType: 'info',
          actionKey: 'open-route',
          routeName: 'purchaseOrder',
          query: { relatedTo: 'resPartner', section: 'ops-financial-trace' },
        },
        {
          key: 'partner-exception-packet',
          title: '冻结伙伴异常包',
          description: '导出当前伙伴异常包，把身份、联系和证据缺口在交接前固定下来。',
          meta: '异常包',
          tone: 'success',
          buttonLabel: '导出异常包',
          buttonType: 'success',
          actionKey: 'export-exception-packet',
        },
      ]
}

function accountMoveShortcuts(isEnglish: boolean): WorkbenchShortcutItem[] {
  return isEnglish
    ? [
        {
          key: 'move-linkage',
          title: 'Payment Linkage Desk',
          description: 'Open the linkage desk to repair invoice anchors, payment refs, and journal continuity from the close cockpit.',
          meta: 'Close / invoice / payment',
          tone: 'warning',
          buttonLabel: 'Open Linkage',
          buttonType: 'warning',
          actionKey: 'open-section',
          section: 'ops-payment-linkage',
        },
        {
          key: 'move-create',
          title: 'New Journal Draft',
          description: 'Open a new draft journal entry directly from the finance closure workbench.',
          meta: 'accountMove.create',
          tone: 'success',
          buttonLabel: 'Create Journal',
          buttonType: 'primary',
          actionKey: 'open-create',
        },
        {
          key: 'move-settlement',
          title: 'Reconciliation Cockpit',
          description: 'Open the shared settlement and reconciliation cockpit for open items, matched lines, and closure pressure.',
          meta: 'Open items / matched lines',
          tone: 'danger',
          buttonLabel: 'Open Cockpit',
          buttonType: 'danger',
          actionKey: 'open-section',
          section: 'ops-settlement',
        },
        {
          key: 'move-payments',
          title: 'Payment Closure Desk',
          description: 'Return to payment artifacts when bank proof or settlement intent needs a stronger anchor.',
          meta: 'accountMove -> accountPayment',
          tone: 'warning',
          buttonLabel: 'Open Payments',
          buttonType: 'warning',
          actionKey: 'open-route',
          routeName: 'accountPayment',
          query: { relatedTo: 'accountMove', section: 'ops-payment-linkage' },
        },
        {
          key: 'move-invoices',
          title: 'Invoice Anchor Desk',
          description: 'Reopen invoices from the journal surface when due date, origin, or partner context needs repair.',
          meta: 'accountMove -> accountInvoice',
          tone: 'info',
          buttonLabel: 'Open Invoices',
          buttonType: 'info',
          actionKey: 'open-route',
          routeName: 'accountInvoice',
          query: { relatedTo: 'accountMove', section: 'ops-settlement' },
        },
        {
          key: 'move-docs',
          title: 'Journal Evidence Desk',
          description: 'Go directly to the top-risk document area and keep closing evidence tied to the journal record.',
          meta: 'Journal evidence',
          tone: 'info',
          buttonLabel: 'Open Documents',
          buttonType: 'info',
          actionKey: 'open-top-risk-documents',
        },
        {
          key: 'move-top-trace',
          title: 'Freeze Top Journal Trace',
          description: 'Export the current top-risk journal trace packet before more cleanup or closing operations accumulate.',
          meta: 'Top trace packet',
          tone: 'success',
          buttonLabel: 'Export Top Trace',
          buttonType: 'success',
          actionKey: 'export-top-trace',
        },
      ]
    : [
        {
          key: 'move-linkage',
          title: '付款联动台',
          description: '打开联动台，从关账驾驶舱修补发票锚点、付款引用和凭证连续性。',
          meta: 'Close / invoice / payment',
          tone: 'warning',
          buttonLabel: '打开联动台',
          buttonType: 'warning',
          actionKey: 'open-section',
          section: 'ops-payment-linkage',
        },
        {
          key: 'move-create',
          title: '新建凭证草稿',
          description: '直接从财务闭环工作台打开新的凭证草稿。',
          meta: 'accountMove.create',
          tone: 'success',
          buttonLabel: '新建凭证',
          buttonType: 'primary',
          actionKey: 'open-create',
        },
        {
          key: 'move-settlement',
          title: '对账驾驶舱',
          description: '打开共享结算与对账驾驶舱，统一审未清项、已匹配分录和关账压力。',
          meta: '未清项 / 已匹配分录',
          tone: 'danger',
          buttonLabel: '打开驾驶舱',
          buttonType: 'danger',
          actionKey: 'open-section',
          section: 'ops-settlement',
        },
        {
          key: 'move-payments',
          title: '付款闭环台',
          description: '当银行凭证或结算意图需要更强锚点时，直接回到付款结果对象。',
          meta: 'accountMove -> accountPayment',
          tone: 'warning',
          buttonLabel: '打开付款',
          buttonType: 'warning',
          actionKey: 'open-route',
          routeName: 'accountPayment',
          query: { relatedTo: 'accountMove', section: 'ops-payment-linkage' },
        },
        {
          key: 'move-invoices',
          title: '发票锚点台',
          description: '当到期日、来源或伙伴上下文需要修补时，直接从凭证界面重开发票。',
          meta: 'accountMove -> accountInvoice',
          tone: 'info',
          buttonLabel: '打开发票',
          buttonType: 'info',
          actionKey: 'open-route',
          routeName: 'accountInvoice',
          query: { relatedTo: 'accountMove', section: 'ops-settlement' },
        },
        {
          key: 'move-docs',
          title: '凭证证据台',
          description: '直达最高风险凭证的文档区，把关账证据固定挂在同一条凭证记录上。',
          meta: '凭证证据',
          tone: 'info',
          buttonLabel: '打开文档',
          buttonType: 'info',
          actionKey: 'open-top-risk-documents',
        },
        {
          key: 'move-top-trace',
          title: '冻结凭证最高追溯包',
          description: '在继续积累更多清理或关账动作前，先导出当前最高风险凭证追溯包。',
          meta: '最高追溯包',
          tone: 'success',
          buttonLabel: '导出最高追溯包',
          buttonType: 'success',
          actionKey: 'export-top-trace',
        },
      ]
}

export function buildFirstWaveWorkbenchShortcuts(
  moduleKey: ModuleKey,
  isEnglish: boolean,
): WorkbenchShortcutItem[] {
  if (moduleKey === 'resPartner') return resPartnerShortcuts(isEnglish)
  if (moduleKey === 'saleOrder') return saleOrderShortcuts(isEnglish)
  if (moduleKey === 'purchaseOrder') return purchaseOrderShortcuts(isEnglish)
  if (moduleKey === 'stockPicking') return stockPickingShortcuts(isEnglish)
  if (moduleKey === 'accountInvoice') return accountInvoiceShortcuts(isEnglish)
  if (moduleKey === 'accountPayment') return accountPaymentShortcuts(isEnglish)
  if (moduleKey === 'accountMove') return accountMoveShortcuts(isEnglish)
  return []
}
